
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxufjaawfditfevbshgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4dWZqYWF3ZmRpdGZldmJzaGdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDQyMTMsImV4cCI6MjA2MjM4MDIxM30.h4mCYx6SOvt_FGaG9sdX9Y6n2b0GAJ77le1nhV36mhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
